# Configuration for .github/workflows/pull_request_label.yaml.

"package-args":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/args/**'

"package-fake_async":
  - changed-files:
      - any-glob-to-any-file: 'pkgs/fake_async/**'
