name: package:lints

on:
  # Run CI on pushes to the main branch, and on PRs against main.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lints.yaml'
      - 'pkgs/lints/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/lints.yaml'
      - 'pkgs/lints/**'
  schedule:
    - cron: "0 0 * * 0"
env:
  PUB_ENVIRONMENT: bot.github

defaults:
  run:
    working-directory: pkgs/lints/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [beta] # todo: re-add stable

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos
      - run: dart tool/validate_lib.dart
      - run: dart tool/gen_docs.dart --verify
